# Generated by Django 5.1.2 on 2024-10-31 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('date_generated', models.DateField(default=django.utils.timezone.now)),
                ('theme', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
